name: bored_g
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_updater: ^0.1.6
    
  hotkey_manager: ^0.1.7
  flutter_map_marker_cluster: any 
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  win32: ^4.1.1
  ffi: ^2.0.1
  positioned_tap_detector_2: ^1.0.4
  tuple: ^2.0.1
  path: ^1.8.2
  quiver: ^3.2.1
  collection: ^1.17.0
  fluttericon: ^2.0.0
  searchfield: ^0.7.5
  cupertino_icons: ^1.0.2
  string_similarity: ^2.0.0
  fuzzywuzzy: ^0.2.0
  easy_debounce: ^2.0.3
  keypress_simulator: ^0.1.0
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
  - chernarusplus_data/
  - offlineMap/loot_tiers.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
